<div class="container mt-5">
    <div class="row mt-5">
        <div class="col-xl-4">
            <div class="card">
                <img src="./assets/img/<?php echo $product["imgUrl"]; ?>" height="300" alt="celular">
                <hr>
                <div class="header-card text-center">
                    <h2><?php echo $product["name"]; ?></h2>
                    <p><?php echo $product["description"]; ?></p>
                    <h4>$<?php echo $product["price"]; ?></h4>
                </div>
            </div>
        </div>
        <div class="col-xl-8">
            <div class="container text-center">
                <h2 class="mb-5">Comprá con Mercado Pago</h2>
                <div class="mt-5">
                    <button>Pagar la compra</button>
                </div>
            </div>
        </div>
    </div>
</div>