<div style="width: 25%;" class="container mt-5 text-center">
    <div class="card">
        <h2>Estado del Pago: <?php echo  $_POST['payment_status']; ?></h2>
        <div class="header-card text-center">
            <p>Preference_ID: <?php echo  $_POST['preference_id']; ?></p>
            <p>Payment_status: <?php echo $_POST["payment_id"]; ?></p>
            <p>Back_url<?php echo $_POST["back_url"]; ?></p>
            <p>si el autoreturn anduviera se podría implemetar mejor</p>
        </div>
    </div>    
</div>
